<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
    public function getCourses($sId)
        {
            $em = $this->getEntityManager();
            $query = $em->createQuery(
                'SELECT c
                FROM AppBundle:Course c
                JOIN c.students s 
                WHERE s.studentId = :stdId'
            )->setParameter('stdId', $sId);
            return $query->getResult();
        }       
    public function getCourseBysecId($secId)
        {
            $em = $this->getEntityManager();
            $query = $em->createQuery(
                'SELECT c
                FROM AppBundle:Course c
                JOIN c.sections s 
                WHERE s.id = :secId'
            )->setParameter('secId', $secId);
            return $query->getSingleResult();
        }
}